### ISSUE TITLE
Server crash on load

### ISSUE THREAD

**Issue by darkphan** [vadis365/Animalium#8] opened 2020-05-10 23:33 UTC
Version: Animalium-0.5.2
Forge: 1.15.2 - 31.1.77
Crashlog: https://gist.github.com/darkphan/af0bca03401bdd1b1753e68910ddca19

**Comment by vadis365** [comment] 2020-05-11 14:39
hhhhnnnnnngggghhhh.

**Comment by vadis365** [comment] 2020-05-11 15:51
Only thing using anything remotely like that is the rats' held items, I've changed the render method now, to how it used to be done, and have a build - no idea if it still has the same issue. I don't have a modded server set up thesedays to test things :( 
Let me know if you would like the build to test (not trying to shill free testing, but kinda ;) )

**Comment by mr-poyo** [comment] 2020-05-11 22:02
Also getting this crash on my server on launch. Using a custom pack so i don't know if logs are good to compare: https://pastebin.com/rVdYNAQK

**Comment by vadis365** [comment] 2020-05-11 22:21
Should be fixed in 1.15.2 now (0.5.3 under review on curse as I type this) - looks like it was an event loading wrong and messing stuff up.
Will backport the fix to 1.15.1 and 1.14.4 if it is confirmed OK in this version as it looks like it was happening for a while in other versions too.
*Edit now approved on curse

**Comment by mr-poyo** [comment] 2020-05-11 22:45
While I can't speak for everyone else. 0.5.3 seems to have resolved the crash from the pastebin i posted. Thank you!

**Comment by vadis365** [comment] 2020-07-11 00:11
Closing due to no further reports - I think it is fixed ;)

**Closed as completed by vadis365** 2020-07-11 00:11 UTC
