### ISSUE TITLE
Server crash while starting up.

### ISSUE THREAD

**Issue by Darkfiend009** [vadis365/Animalium#3] opened 2020-01-13 21:18 UTC
Server crashes while attempting to launch.

Mod Version: Animalium 0.5.1
Forge Version: 30.0.30
Minecraft Version: 1.15.1

Crash Report: 
https://pastebin.com/EpcJ7YYv

**Comment by ghost** [comment] 2020-01-21 19:29
I have the same problem.

**Comment by KnifeOfDunwall** [comment] 2020-04-16 13:58
me too. only on 1.14.4

**Comment by vadis365** [comment] 2020-05-11 22:28
I think I have fixed this in a later version now and will backport if it is confirmed OK.
see #8 as it is an identical report.

**Comment by vadis365** [comment] 2020-07-11 00:11
Closing because it is fixed in the last 2 game versions.

**Closed as completed by vadis365** 2020-07-11 00:11 UTC
